# Generated by Django 4.2.6 on 2023-10-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('allDay', models.BooleanField()),
                ('wheelchair_serviceCapability', models.CharField(max_length=15)),
                ('wheelchair_serviceActivity', models.CharField(max_length=15)),
                ('blind_serviceCapability', models.CharField(max_length=15)),
                ('blind_serviceActivity', models.CharField(max_length=15)),
                ('nfcForBankCards_serviceCapability', models.CharField(max_length=15)),
                ('nfcForBankCards_serviceActivity', models.CharField(max_length=15)),
                ('qrRead_serviceCapability', models.CharField(max_length=15)),
                ('qrRead_serviceActivity', models.CharField(max_length=15)),
                ('supportsUsd_serviceCapability', models.CharField(max_length=15)),
                ('supportsUsd_serviceActivity', models.CharField(max_length=15)),
                ('supportsChargeRub_serviceCapability', models.CharField(max_length=15)),
                ('supportsChargeRub_serviceActivity', models.CharField(max_length=15)),
                ('supportsEur_serviceCapability', models.CharField(max_length=15)),
                ('supportsEur_serviceActivity', models.CharField(max_length=15)),
                ('supportsRub_serviceCapability', models.CharField(max_length=15)),
                ('supportsRub_serviceActivity', models.CharField(max_length=15)),
            ],
        ),
    ]
