# Generated by Django 4.2.6 on 2023-10-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=50, max_digits=50)),
                ('longitude', models.DecimalField(decimal_places=50, max_digits=50)),
                ('allDay', models.BooleanField()),
                ('wheelchair_serviceCapability', models.CharField(max_length=50)),
                ('wheelchair_serviceActivity', models.CharField(max_length=50)),
                ('blind_serviceCapability', models.CharField(max_length=50)),
                ('blind_serviceActivity', models.CharField(max_length=50)),
                ('nfcForBankCards_serviceCapability', models.CharField(max_length=50)),
                ('nfcForBankCards_serviceActivity', models.CharField(max_length=50)),
                ('qrRead_serviceCapability', models.CharField(max_length=50)),
                ('qrRead_serviceActivity', models.CharField(max_length=50)),
                ('supportsUsd_serviceCapability', models.CharField(max_length=50)),
                ('supportsUsd_serviceActivity', models.CharField(max_length=50)),
                ('supportsChargeRub_serviceCapability', models.CharField(max_length=50)),
                ('supportsChargeRub_serviceActivity', models.CharField(max_length=50)),
                ('supportsEur_serviceCapability', models.CharField(max_length=50)),
                ('supportsEur_serviceActivity', models.CharField(max_length=50)),
                ('supportsRub_serviceCapability', models.CharField(max_length=50)),
                ('supportsRub_serviceActivity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salePointName', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('rko', models.CharField(max_length=50)),
                ('officeType', models.CharField(max_length=50)),
                ('salePointFormat', models.CharField(max_length=50)),
                ('suoAvailability', models.CharField(max_length=50)),
                ('hasRamp', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=50, max_digits=50)),
                ('longitude', models.DecimalField(decimal_places=50, max_digits=50)),
                ('metroStation', models.CharField(blank=True, max_length=255, null=True)),
                ('distance', models.IntegerField()),
                ('kep', models.BooleanField()),
                ('myBranch', models.BooleanField()),
                ('ul_mon', models.CharField(max_length=255)),
                ('ul_tue', models.CharField(max_length=255)),
                ('ul_wen', models.CharField(max_length=255)),
                ('ul_thu', models.CharField(max_length=255)),
                ('ul_fri', models.CharField(max_length=255)),
                ('ul_sat', models.CharField(max_length=255)),
                ('ul_san', models.CharField(max_length=255)),
                ('fl_mon', models.CharField(max_length=255)),
                ('fl_tue', models.CharField(max_length=255)),
                ('fl_wen', models.CharField(max_length=255)),
                ('fl_thu', models.CharField(max_length=255)),
                ('fl_fri', models.CharField(max_length=255)),
                ('fl_sat', models.CharField(max_length=255)),
                ('fl_san', models.CharField(max_length=255)),
            ],
        ),
    ]
