# -*- coding: windows-1251 -*
# Generated by Django 4.2.6 on 2023-10-13 18:54

from django.db import migrations


def create_data(apps, schema_editor):
    ATM = apps.get_model('main', 'atms')

    atms_data = [
        {
            "address": "ул. Богородский Вал, д. 6, корп. 1",
            "latitude": 55.802432,
            "longitude": 37.704547,
            "allDay": False,
            "wheelchair_serviceCapability": "UNKNOWN",
            "wheelchair_serviceActivity": "UNKNOWN",
            "blind_serviceCapability": "UNKNOWN",
            "blind_serviceActivity": "UNKNOWN",
            "nfcForBankCards_serviceCapability": "UNKNOWN",
            "nfcForBankCards_serviceActivity": "UNAVAILABLE",
            "qrRead_serviceCapability": "UNSUPPORTED",
            "qrRead_serviceActivity": "UNAVAILABLE",
            "supportsUsd_serviceCapability": "UNSUPPORTED",
            "supportsUsd_serviceActivity": "UNAVAILABLE",
            "supportsChargeRub_serviceCapability": "SUPPORTED",
            "supportsChargeRub_serviceActivity": "AVAILABLE",
            "supportsEur_serviceCapability": "UNSUPPORTED",
            "supportsEur_serviceActivity": "UNAVAILABLE",
            "supportsRub_serviceCapability": "SUPPORTED",
            "supportsRub_serviceActivity": "AVAILABLE"
        },
        {
            "address": "ул. Нижняя Красносельская, д. 43",
            "latitude": 55.773763,
            "longitude": 37.675002,
            "allDay": False,
            "wheelchair_serviceCapability": "UNKNOWN",
            "wheelchair_serviceActivity": "UNKNOWN",
            "blind_serviceCapability": "UNKNOWN",
            "blind_serviceActivity": "UNKNOWN",
            "nfcForBankCards_serviceCapability": "UNKNOWN",
            "nfcForBankCards_serviceActivity": "UNAVAILABLE",
            "qrRead_serviceCapability": "UNSUPPORTED",
            "qrRead_serviceActivity": "UNAVAILABLE",
            "supportsUsd_serviceCapability": "UNSUPPORTED",
            "supportsUsd_serviceActivity": "UNAVAILABLE",
            "supportsChargeRub_serviceCapability": "SUPPORTED",
            "supportsChargeRub_serviceActivity": "AVAILABLE",
            "supportsEur_serviceCapability": "UNSUPPORTED",
            "supportsEur_serviceActivity": "UNAVAILABLE",
            "supportsRub_serviceCapability": "SUPPORTED",
            "supportsRub_serviceActivity": "AVAILABLE"
        },
        {
            "address": "ул. Авиаконструктора Миля, д. 4, корп. 1",
            "latitude": 55.686137,
            "longitude": 37.849832,
            "allDay": False,
            "wheelchair_serviceCapability": "UNKNOWN",
            "wheelchair_serviceActivity": "UNKNOWN",
            "blind_serviceCapability": "UNKNOWN",
            "blind_serviceActivity": "UNKNOWN",
            "nfcForBankCards_serviceCapability": "UNKNOWN",
            "nfcForBankCards_serviceActivity": "UNAVAILABLE",
            "qrRead_serviceCapability": "UNSUPPORTED",
            "qrRead_serviceActivity": "UNAVAILABLE",
            "supportsUsd_serviceCapability": "UNSUPPORTED",
            "supportsUsd_serviceActivity": "UNAVAILABLE",
            "supportsChargeRub_serviceCapability": "SUPPORTED",
            "supportsChargeRub_serviceActivity": "AVAILABLE",
            "supportsEur_serviceCapability": "UNSUPPORTED",
            "supportsEur_serviceActivity": "UNAVAILABLE",
            "supportsRub_serviceCapability": "SUPPORTED",
            "supportsRub_serviceActivity": "AVAILABLE"
        }
    ]

    for data in atms_data:
        ATM.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
