# Generated by Django 4.2.6 on 2023-10-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_atms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salePointName', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=15)),
                ('rko', models.CharField(max_length=15)),
                ('officeType', models.CharField(max_length=15)),
                ('salePointFormat', models.CharField(max_length=15)),
                ('suoAvailability', models.CharField(max_length=1)),
                ('hasRamp', models.CharField(max_length=1)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('metroStation', models.CharField(blank=True, max_length=255, null=True)),
                ('distance', models.IntegerField()),
                ('kep', models.BooleanField()),
                ('myBranch', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OpenHoursIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=10)),
                ('hours', models.CharField(max_length=20)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.offices')),
            ],
        ),
        migrations.CreateModel(
            name='OpenHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=10)),
                ('hours', models.CharField(max_length=20)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.offices')),
            ],
        ),
    ]
